select 
  CA.ACCOUNT_NAME NAME,
	CA.PARTY_ID PARTY_ID,
	CA.CUSTOMER_TYPE ACCOUNT_TYPE_CODE,
	CA.CUSTOMER_CLASS_CODE ACCOUNT_CLASS_CODE,
	CASE
	WHEN CA.STATUS='A' THEN 'Y'
	ELSE	'N'
END ACTIVE_FLG,
	CA.FREIGHT_TERM FRGHT_TERMS_CODE,
	CA.ACCOUNT_ESTABLISHED_DATE ACCOUNT_SINCE_DATE,
	CA.ACCOUNT_NUMBER ACCOUNT_NUM,
	CA.PAYMENT_TERM_ID PAY_TERMS_CODE,
	CA.CREATED_BY CREATED_BY_ID,
	CA.LAST_UPDATED_BY CHANGED_BY_ID,
	CA.CREATION_DATE CREATED_ON_DT,	
  CA.LAST_UPDATE_DATE
  CHANGED_ON_DT,
	CA.TAX_CODE TAX_CODE,
	CA.AUTOPAY_FLAG AUTOPAY_FLG,
	CA.HOLD_BILL_FLAG HOLD_BILL_FLG,
	CA.CUST_ACCOUNT_ID CUST_ACCOUNT_ID,
	'0' X_CUSTOM,
  'N'
  DELETE_FLG,
	CA.ATTRIBUTE1 X_SOLDTO_CUST_PARENT
from	"PC_FIVETRAN_DB"."ERPPRD_AR"."HZ_CUST_ACCOUNTS" CA
where	(1=1)
And (
(CA.LAST_UPDATE_DATE > TO_DATE(SUBSTR('2002-01-23 11:23:08',0,19),'YYYY-MM-DD HH24:MI:SS'))
)
