select 
          DISTINCT
                   ACCT_ROLE.CUST_ACCOUNT_ROLE_ID CONTACT_ID,
                ACCT_ROLE.CUST_ACCOUNT_ID CUSTOMER_ID,
                ACCT_ROLE.CUST_ACCT_SITE_ID ADDRESS_ID,
                ACCT_ROLE.LAST_UPDATE_DATE LAST_UPDATE_DATE,
                ACCT_ROLE.OBJECT_VERSION_NUMBER OBJECT_VERSION,
                ACCT_ROLE.LAST_UPDATED_BY LAST_UPDATED_BY,
                ACCT_ROLE.CREATION_DATE CREATION_DATE,
                ACCT_ROLE.CREATED_BY CREATED_BY,
                ACCT_ROLE.LAST_UPDATE_LOGIN LAST_UPDATE_LOGIN,
                PARTY.PERSON_FIRST_NAME FIRST_NAME,
                PARTY.PERSON_LAST_NAME LAST_NAME,
                ACCT_ROLE.STATUS STATUS,
                ORG_CONT.MAIL_STOP MAIL_STOP,
                ACCT_ROLE.ORIG_SYSTEM_REFERENCE ORIG_SYSTEM_REFERENCE,
                PARTY.CUSTOMER_KEY CONTACT_KEY,
                REL_PARTY.EMAIL_ADDRESS EMAIL_ADDRESS,
                REL_PARTY.PRIMARY_PHONE_AREA_CODE||REL_PARTY.PRIMARY_PHONE_NUMBER PHONE_NUMBER,
                REL_PARTY.PARTY_ID CONTACT_PARTY_ID,
                ORG_CONT.ORG_CONTACT_ID ORG_CONTACT_ID,
                ORG_CONT.CONTACT_NUMBER CONTACT_NUMBER,
                PARTY.LAST_UPDATE_DATE PARTY_LAST_UPDATE_DATE,
                PARTY.OBJECT_VERSION_NUMBER PARTY_OBJECT_VERSION_NUMBER,
                REL.LAST_UPDATE_DATE REL_LAST_UPDATE_DATE,
                ORG_CONT.LAST_UPDATE_DATE ORG_CONT_LAST_UPDATE_DATE,
                ORG_CONT.OBJECT_VERSION_NUMBER ORG_OBJ_VERSION_NUMBER,
                REL.RELATIONSHIP_ID REL_RELATIONSHIP_ID,
                REL_PARTY.LAST_UPDATE_DATE REL_PARTY_LAST_UPDATE_DATE,
                REL_PARTY.PARTY_ID REL_PARTY_ID,
                REL.OBJECT_VERSION_NUMBER REL_OBJECT_VERSION_NUMBER,
                CONT_POINT.OBJECT_VERSION_NUMBER CONT_POINT_OBJECT_VERSION
from      "PC_FIVETRAN_DB"."EBSUAT_AR"."HZ_CONTACT_POINTS"
   CONT_POINT, 
  "PC_FIVETRAN_DB"."EBSUAT_AR"."HZ_CUST_ACCOUNT_ROLES" ACCT_ROLE, 
  "PC_FIVETRAN_DB"."EBSUAT_AR"."HZ_PARTIES"
   PARTY, "PC_FIVETRAN_DB"."EBSUAT_AR"."HZ_PARTIES"   REL_PARTY, 
  "PC_FIVETRAN_DB"."EBSUAT_AR"."HZ_RELATIONSHIPS" REL, 
  "PC_FIVETRAN_DB"."EBSUAT_AR"."HZ_ORG_CONTACTS" ORG_CONT, 
 "PC_FIVETRAN_DB"."EBSUAT_AR"."HZ_CUST_ACCOUNTS" ROLE_ACCT, 
  "PC_FIVETRAN_DB"."ERPUAT_AR"."HZ_PERSON_LANGUAGE"   PER_LANG, 
  "PC_FIVETRAN_DB"."ERPUAT_AR"."HZ_CONTACT_PREFERENCES" CONT_RES
where   (1=1)
And (PARTY.PARTY_ID = CONT_RES.CONTACT_PREFERENCE_ID(+))
AND (ACCT_ROLE.PARTY_ID = REL.PARTY_ID
AND ACCT_ROLE.ROLE_TYPE = 'CONTACT')
AND (ORG_CONT.PARTY_RELATIONSHIP_ID = REL.RELATIONSHIP_ID)
AND (REL.SUBJECT_ID = PARTY.PARTY_ID)
AND (REL_PARTY.PARTY_ID = REL.PARTY_ID)
AND (CONT_POINT.OWNER_TABLE_ID(+) = REL_PARTY.PARTY_ID)
AND (ACCT_ROLE.CUST_ACCOUNT_ID = ROLE_ACCT.CUST_ACCOUNT_ID)
AND (ROLE_ACCT.PARTY_ID = REL.OBJECT_ID)
AND (PARTY.PARTY_ID = PER_LANG.PARTY_ID(+))

And (CONT_RES.CONTACT_LEVEL_TABLE(+) = 'HZ_PARTIES')
And (CONT_POINT.CONTACT_POINT_TYPE(+)='EMAIL')
And (CONT_POINT.PRIMARY_FLAG(+)='Y')
And (PER_LANG.NATIVE_LANGUAGE(+) = 'Y')
And (CONT_POINT.OWNER_TABLE_NAME(+) = 'HZ_PARTIES')
